before_install:
  - sudo apt-get -qq update
  - sudo apt-get install lcov

install:
  - wget https://github.com/libcheck/check/releases/download/0.11.0/check-0.11.0.tar.gz
  - tar -xzvf check-0.11.0.tar.gz
  - pushd check-0.11.0 && ./configure --prefix=/usr && make && sudo make install && popd
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
